### ISSUE TITLE
Verify RS256 JWT signature without private key

### ISSUE THREAD

**Issue by AnasASK** [fenix-hub/godot-engine.jwt#15]
Many tools online only require the public key to verify the JWT signature
example: https://developer.pingidentity.com/en/tools/jwt-decoder.html

In the documentation section of this addon to Verify RS256 JWT:
```
var private_key: CryptoKey = CryptoKey.new()
var public_key: CryptoKey = CryptoKey.new()
private_key.load_from_string("<your private key PEM string>", false)
public_key.load_from_string("<your public key PEM string>", true)

var jwt: String = "<a jwt>"
var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.RS256(public_key)
var jwt_verifier: JWTVerifier = JWT.require(jwt_algorithm) \
    .with_claim("id","someid") \
    .build() # Reusable Verifier
if jwt_verifier.verify(jwt) == JWTVerifier.JWTExceptions.OK :
	print("Verified!")
else:
	print(jwt_verifier.exception)
```
How can I skip verifying the algorithm here `JWT.require(jwt_algorithm)` ? I only need to verify the signature and claims.

**Comment by fenix-hub** [comment]
If you just want to verify, you can skip the `private_key` initialization as well. Then, you can use the [verify_signature()](https://github.com/fenix-hub/godot-engine.jwt/blob/db7df550efdbf60c0241f6698826232ada0a6646/addons/jwt/src/JWTVerifier.gd#L29) method to verify only the signature, and [verify_claim_values()](https://github.com/fenix-hub/godot-engine.jwt/blob/db7df550efdbf60c0241f6698826232ada0a6646/addons/jwt/src/JWTVerifier.gd#L33) to verify all or some of the claims.
```gdscript
# verify signature
if jwt_verifier.verify_signature(JWTDecoder.new(jwt)):
	print("Valid!")
else:
	print(jwt_verifier.exception)

# verify specific claims
if jwt_verifier.verify_claim_values(JWTDecoder.new(jwt), { my_claim = "my_value" }):
	print("Valid!")
else:
	print(jwt_verifier.exception)

# verify claims previously provided to the verifier with `with_claim()` method
if jwt_verifier.verify_claim_values(JWTDecoder.new(jwt), jwt_verifier.claims):
	print("Valid!")
else:
	print(jwt_verifier.exception)
```
You can't skip the algorithm verification, since you need to provide the algorithm that was used to generate your JWT. (`JWT.require()` doesn't "verify" the algorithm, but asks what algorithm should be used to verify the signature). If some tools online don't ask you the algorithm, it's because they are taking it from the JWT header, but it's always best to provide the algorithm to the verifier.

**Comment by fenix-hub** [comment]
By the way `jwt_verifier.verify()` does all of that for you plus some other verification, so I suggest you to just use that instead :)
[Take a look here](https://github.com/fenix-hub/godot-engine.jwt/blob/db7df550efdbf60c0241f6698826232ada0a6646/addons/jwt/src/JWTVerifier.gd#L92-L100)

**Comment by AnasASK** [comment]
Thank you for your help,


> `JWT.require()` doesn't "verify" the algorithm, but asks what algorithm should be used to verify the signature

> `jwt_verifier.verify()` does all of that for you plus some other verification, so I suggest you to just use that instead

Yes, what I meant to say is that I need to provide public and private keys to even get that `jwt_verifier` variable
```
var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.RS256(public_key, private_key)
var jwt_verifier: JWTVerifier = JWT.require(jwt_algorithm) \
    .with_claim("id","someid") \
    .build() # Reusable Verifier
```
`jwt_algorithm` variable requires public and private keys... and `JWT.require()` requires `jwt_algorithm`
In other words, cannot skip the private_key initialization if I where to simply call `jwt_verifier.verify()` since `jwt_verifier` needs a private key.. I hope my issue made sense.

**Comment by fenix-hub** [comment]
Oh yes, that makes sense now, but you can just set the `private_key = null` or just not loading any key, and verification will work anyway :)
```gdscript
var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.RS256(public_key, CryptoKey.new())
# or
var jwt_algorithm: JWTAlgorithm = JWTAlgorithmBuilder.RS256(public_key, null)`

**Comment by AnasASK** [comment]
Okay, thanks for the clarification. It is working now :)
